apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hmily-admin.fullname" . }}
  labels:
    {{- include "hmily-admin.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hmily-admin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hmily-admin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hmily-admin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{/* check if database type is valid */}}
      {{- $dataSourceTypeValid := has .Values.dataSource.active (list "mysql") -}}
      {{- if not $dataSourceTypeValid -}}{{- required "Invalid `.dataSource.active`. Must be one of 'mysql'" -}}{{- end}}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          volumeMounts:
            - name: hmily-admin-config
              mountPath: /opt/hmily-admin/conf/application.yml
              subPath: application.yml
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: hmily-admin-config
              mountPath: /opt/hmily-admin/conf/application.yml
              subPath: application.yml
          {{- if eq .Values.dataSource.active "mysql" }}
            - name: hmily-admin-config
              mountPath: /opt/hmily-admin/conf/application-mysql.yml
              subPath: application-mysql.yml
          {{- end}}
      volumes:
        - name: hmily-admin-config
          configMap:
            name: {{ include "hmily-admin.fullname" . }}
            items:
              - key: application.yml
                path: application.yml
            {{- if eq .Values.dataSource.active "mysql" }}
              - key: application-mysql.yml
                path: application-mysql.yml
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
